[project]
name = "callee"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "matsu", email = "tmtmt2209@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
callee = "callee:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
